DEFINE SHARED VARIABLE XCodeKey         AS CHARACTER NO-UNDO.
DEFINE SHARED VARIABLE SourceFileFull   AS CHARACTER NO-UNDO.
DEFINE SHARED VARIABLE CodeListFile     AS CHARACTER NO-UNDO.
DEFINE SHARED VARIABLE DebugListFile    AS CHARACTER NO-UNDO.
DEFINE SHARED VARIABLE RCodePath        AS CHARACTER NO-UNDO.
DEFINE SHARED VARIABLE Langs        AS CHARACTER NO-UNDO.
DEFINE SHARED VARIABLE TextSegGrow        AS INTEGER NO-UNDO.
DEFINE SHARED VARIABLE MultiCompile        AS CHARACTER NO-UNDO.
COMPILER:MULTI-COMPILE = LOGICAL(MultiCompile).
COMPILE VALUE(SourceFileFull) SAVE NO-ERROR.
